-- Di cmd run connect to psql database then run this: 
-- COPY public.movies (id, title, genres, year) FROM '$$PATH$$3319.dat';
-- \COPY public.users (id, email, gender, password, role) FROM '$$PATH$$3318.dat';